config/routes.rb
Rails.application.routes.draw do

  resources :messengers
  devise_for :users
  resources :services
  root 'pages#landing'

  %q{get '/about' => 'pages#about'

  get '/contact' => 'pages#contact'

  get '/faqs' => 'pages#faqs'

  get '/qanda' => 'pages#srrp'}

end

app/models/service.rb
class Service < ActiveRecord::Base
   
   extend FriendlyId
   friendly_id :name, :use => :slugged

   has_attached_file :image, :styles => { :medium => "400x400>", :thumb => "100x100>"}, default_url: "kevin.jpg"
	
   validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
    respond_to do |format|
      format.html { render :show }
      
      format.pdf do
        pdf = Prawn::Document.new
        pdf.text @service.description
        send_data pdf.render,
          filename: "export.pdf",
          type: 'application/pdf',
          disposition: 'inline'
      end
    end
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description, :image)
    end


end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for @service, html: {multipart: true} do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<div id="content" class="site-content">

      

<div class="header-title without-cap text-center" style="background: url(https://s3.amazonaws.com/sparta30/photo/danny-howe-365401.jpg); background-size: cover;">
  <div class="title-wrap">
    <div class="content">
    
      <div class="full-width-container">
        <h1 class="page-title">Sparta Inc.</h1>
                  <br>
          <p class="subtitle">Know your Music. Master your Craft.</p>
              </div>

    </div>
  </div>
</div> <!-- .header-title -->



<div class="full-width-container">
  <div class="vc_col-sm-12">
    <div id="primary" class="content-area">
      <main id="main" class="site-main">
        <article id="post-701" class="post-701 page type-page status-publish hentry">
  <div class="entry-content">
    <div class="vc_row wpb_row vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"><div class="vc_empty_space  arg-spacer"   style="height: 100px" ><span class="vc_empty_space_inner"></span></div>
</div></div></div></div><div class="vc_row wpb_row vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-3"><div class="vc_column-inner "><div class="wpb_wrapper"><div id="argenta-custom-5a6eefa072abb"  class="heading-wrapper text-left"  >
  
  <div class="container">
<div class="row">
  <% @services.reverse.each do |service| %>
      <div class="col-md-4">
  <div class="thumbnail">
        <%= link_to image_tag(service.image.url (:medium)), service %>
        <div class="caption">
        <h5 ><%= link_to service.name, service %></h5>

        <% if user_signed_in? && current_user.admin? %>
        
        <%= link_to 'Show', service %>
        <%= link_to 'Edit', edit_service_path(service) %>
        <%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %>

        <% end %>

    </div>  
      </div>
     
      </div> 
      <% end %>
      </div>
      </div>

  
 
<% if user_signed_in? && current_user.admin? %>

<%= link_to 'New Service', new_service_path %>

<% end %> 
  </div> </div></div></div></div></div></article></main></div></div></div></div> 


   











 

   

app/views/services/new.html.erb
<br><br><br><div class="container"><h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %></div>

app/views/services/show.html.erb
<div id="content" class="site-content">

      

<div class="header-title without-cap text-center" style="background: url(https://s3.amazonaws.com/sparta30/photo/danny-howe-365401.jpg); background-size: cover;">
  <div class="title-wrap">
    <div class="content">
    
      <div class="full-width-container">
        <h1 class="page-title">Sparta Inc.</h1>
                  <br>
          <p class="subtitle">Know your Music. Master your Craft.</p>

              </div>

    </div>
  </div>
</div> <!-- .header-title -->



<div class="full-width-container">
  <div class="vc_col-sm-12">
    <div id="primary" class="content-area">
      <main id="main" class="site-main">
        <article id="post-701" class="post-701 page type-page status-publish hentry">
  <div class="entry-content">
    <div class="vc_row wpb_row vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"><div class="vc_empty_space  arg-spacer"   style="height: 100px" ><span class="vc_empty_space_inner"></span></div>
</div></div></div></div><div class="vc_row wpb_row vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-3"><div class="vc_column-inner "><div class="wpb_wrapper"><div id="argenta-custom-5a6eefa072abb"  class="heading-wrapper text-left"  >




<div class=" container">
<h1><%= @service.name.upcase %></h1>
  
<div class="row">
 

 <div class="col-md-4">
     

 <div class="thumbnail">  
<%= link_to image_tag(@service.image.url (:medium)), @service %>
</div>


  
  


</div>
      

<div class="col-md-6">
<p>
  
  <%= markdown(@service.description) %>
</p>
</div>

</div>
<% if user_signed_in? && current_user.admin? %>
<%= link_to 'Edit', edit_service_path(@service) %> |
<% end %>

<%= link_to 'Back', services_path %><br><br><br>
</div>
</div></div>
  
   
  </div> </div></div></div></div></div></article></main></div></div></div></div> 


   











 

   