config/routes.rb
Rails.application.routes.draw do

  resources :messengers
  devise_for :users
  resources :services
  root 'pages#landing'

  %q{get '/about' => 'pages#about'

  get '/contact' => 'pages#contact'

  get '/faqs' => 'pages#faqs'

  get '/qanda' => 'pages#srrp'}

end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/about.html.erb
<div id="content" class="site-content">

      

<div class="header-title without-cap text-center" style="background: url(https://s3.amazonaws.com/sparta30/photo/danny-howe-365401.jpg); background-size: cover;">
  <div class="title-wrap" style="height: -200px;">
    <div class="content">
    
      <div class="full-width-container">
        <h1 class="page-title">Sparta Inc.</h1>
                  <br>
          <p class="subtitle" style="color: white;">Know your Music. Master your Craft.</p>
              </div>

    </div>
  </div>
</div> <!-- .header-title -->
<div id="content" class="site-content">

			




<div class="full-width-container">
	<div class="vc_col-sm-12">
		<div id="primary" class="content-area">
			<main id="main" class="site-main">
				<article id="post-550" class="post-550 page type-page status-publish hentry">
	<div class="entry-content">
		<div data-vc-full-width="true" data-vc-full-width-init="false" data-vc-stretch-content="true" class="vc_row wpb_row vc_row-fluid vc_row-no-padding"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"><div class="split-box" id="argenta-custom-5a6e0ce91a6f0" 
	data-parallax-left="vertical"		data-parallax-speed-left="0.5"	>
		<div class="vc_col-md-6 split-box-wrap">
		<div class="parallax-bg" style="background: url( ); background-size: cover;"></div>
		<div class="content"><img class="size-medium wp-image-4477 aligncenter" src="https://s3.amazonaws.com/sparta30/photo/harry.jpg" alt="photo_02_zoltan_szirmai1132" width="300" height="191" srcset="https://s3.amazonaws.com/sparta30/photo/harry.jpg" sizes="(max-width: 559px) 100vw, 559px" />
					</div>
	</div>	<div class="vc_col-md-6 split-box-wrap">
		<div class="parallax-bg" style="background-color:#987F71;"></div>
		<div class="content">
			<div class="vc_empty_space"   style="height: 100px" ><span class="vc_empty_space_inner"></span></div>
<div id="argenta-custom-5a6e0ce91b10a"  class="heading-wrapper text-left"  >
			<p class="subtitle">Hello,</p>
	
	<h3 class="second-title text-left" style="font-size: 50px;">Harry Okoh</h3>

	
	
	</div>	

<div id="argenta-custom-5a6e0ce91b2be"  >
	<p style="text-align: left;"><span style="color: #ffffff;">Principal Consultant</span></p>
</div>

<div class="vc_empty_space"   style="height: 5px" ><span class="vc_empty_space_inner"></span></div>

	<div class="wpb_text_column wpb_content_element " >
		<div class="wpb_wrapper">
			<p><span style="color: #d6d0c7;">Established in 2010, Sparta Inc is a music resource boutique that specializes in providing A&R assessment/coordination for Hip Hop/R&B artists and record labels in Nigeria.<br>
It serves as a clearing house for rappers, singers,  songwriters, producers and recording DJs, providing quality assurance for their compositions and recordings.<br><br>
Mr. Harry Okoh, a seasoned music critic who has worked with such acts as Bez, Darey  Art-Alade, Ill Bliss, Banky W, Suspect, Mo Cheddah e.t.c.,  serves as the principal consultant.</span></p>
 
		</div>
	</div>
<div class="socialbar social-column-5" id="argenta-custom-5a6e0ce91b880"  >

		<a href="https://facebook.com/spartaincnigeria " target="_blank" class="social facebook rounded">
		<span class="fa fa-facebook "></span>
			</a>
	
		<a href="https://twitter.com/spartaincnigeria " target="_blank" class="social twitter rounded">
		<span class="fa fa-twitter"></span>
			</a>
	
		
	
	
</div>

		</div>
	</div>	
</div>

</div></div></div></div><div class="vc_row-full-width vc_clearfix"></div> </div></article></main></div></div></div></div>


  </div> </div></div></div></div>

         

<!--<div class="jumbotron" style="height: 500px;">
	<h1 style="text-align: center; margin-top:150px; color: white; font-size: 80px; font-family: Copperplate Gothic Light, sans-serif;  ">SPARTA INC.</h1><p style="text-align: center; color: white; font-size: 25px;">Know your music. Master your craft.</p>
</div>-->
 
			 

app/views/pages/contact.html.erb
<div id="content" class="site-content">

      

<div class="header-title without-cap text-center" style="background: url(https://s3.amazonaws.com/sparta30/photo/danny-howe-365401.jpg); background-size: cover;">
  <div class="title-wrap">
    <div class="content">
    
      <div class="full-width-container">
        <h1 class="page-title">Sparta Inc.</h1>
                  <br>
          <p class="subtitle">Know your Music. Master your Craft.</p>
              </div>

    </div>
  </div>
</div> <!-- .header-title -->

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/faqs.html.erb
<div id="content" class="site-content">

      

<div class="header-title without-cap text-center" style="background: url(https://s3.amazonaws.com/sparta30/photo/danny-howe-365401.jpg); background-size: cover;">
  <div class="title-wrap">
    <div class="content">
    
      <div class="full-width-container">
        <h1 class="page-title">Sparta Inc.</h1>
                  <br>
          <p class="subtitle">Know your Music. Master your Craft.</p>
              </div>

    </div>
  </div>
</div> <!-- .header-title -->
<div class="container">
					<h1>Frequently Asked Questions(FAQs)</h1><span class="heading-b3" style="margin-top:px; margin-bottom:px; background-color:#000000"></span>				 
			<div class="entry">

<p><strong>Q: What does A&R mean?</strong><br>
A: A&R means Artist and Repertoire.<br><br>

<p><strong>Q: What does an A&R consultant do?</strong><br>
A: An A&R consultant is like a talent scout, supervising producer and music tastemaker rolled in one. In a developed music industry he is a key personnel at a record label, responsible for identifying and signing new talents to the label. It is also his duty to oversee recordings for an album, select tracks for the album, screen proposed titles for songs and the album, and in some cases arrange the tracklist. He also takes part of the responsibility for the naming and imagining of new acts. Its his job to ensure that the master recording is commercially/technically satisfactory i.e. basically eliminating the chance of rejection when it is submitted to the label’s top brass. In the Nigerian music industry his primary responsibility is to “proof-hear” recordings, making sure the work is of the highest quality, creatively and technically. He basically tries to eliminate fillers from your recordings leaving only gems that will be recognised by music critics and loved by the target audience.<br><br>

<p><strong>Q: Why do I need an A&R consultant to assess me and my work? People that have heard my songs say I’m the bomb!</strong><br>
A: If you’re a newbie in the industry it wouldn’t be suprising if most of these “people” are family and friends. It is incumbent upon them to encourage you in any legitimate endeavour you choose to pursue. The rest of these “people”, who are more likely to be acquaintances than total strangers, will agree with whatever opinion you have of yourself and your music -  you certainly have some belief in your ability that’s why you bothered to sample their opinion in the first place. It would be impolite for them to say otherwise.This doesn’t mean they aren’t being honest with you. They just cannot be too critical of your work. 
You need an A&R person to assess your work in order to get a dispassionate opinion on whether it will meet your creative and commercial aspirations upon release, all other things remaining equal.<br><br>

<p><strong>Q: Does having an A&R person assess my materials guarantee that I will score a hit?</strong><br>
A: No, it doesn’t guarantee anything. Scoring a major hit is the result of a combination of factors: an album full of great songs; the right singles; a strategic publicity campaign; relentless and extensive promotion of both the singles and album in traditional and new media; near perfect timing of release; the right imaging including career defining performances and videos; and more importantly, the goodwill of the music consuming public – remember, they have a choice not to request for your songs or get ecstatic when it comes on air.
What it does guarantee however is that in the event of your failure to score a major hit, the music will not be one of the reasons why your effort bombed*.
In economics terms, it saves you the cost of undertaking a publicity and promotion campaign which can easily run into millions of naira and yet not achieve its aim.<br><br>

<p><strong>Q: Why do I need them at all when they can’t guarantee anything?</strong><br>
A: That’s exactly why you need them: to help you keep  your head on your shoulders and keep your feet on the ground. Essentially a reality check for you. Their inputs will help you determine whether your talent is for making and performing music or making cup cakes. They help you gain knowledge of your music and mastery of your craft.<br><br>

<p><strong>Q: How is an A&R consultant different from the judges on the numerous talent shows on TV?</strong><br><br>
A: The judges at these talent shows are looking for acts with singing talents and the charisma necessary for success in pop music. Their scrutiny of the contestants is limited to what the format allows i.e. the rendition of pop standards and a few original compositions. Remember, its a show, so the entertainment value of the format is the highest consideration for its creators, including the judges. An A&R session is a more solemn affair. The A&R man’s forte is usually a specific genre; rap/Hip Hop, Jazz, R&B, pop, rock, funk, soul e.t.c. hence he scrutinizes your recordings a lot more closely, making suggestions and recommendations on the creative and technical aspects of your work. His scrutiny of your live performances is very discreet so he can see you do your thing uninhibited.<br><br>

<p><strong>Q: But I rap, I don’t sing. I clearly do not need an A&R assessment, or do I?</strong><br>
A: You certainly do. Even when you rap, you’re making music. You don’t want to fall into the trap of making music for Hip Hop heads only. There’s need to craft your songs in ways that will appeal to people who aren’t necessarily Hip Hop heads.</br><br>

<p><strong>Q: F**k that. I’m fresh to death and I’ve got to a new joint produced by the most in-demand producer in Nigeria, plus I’ve got a soon-to-be-released Clarence Peters video. I’m heading for radio. I’m gonna be a star. Groupies, what are you waiting for?</strong><br>
A: In that case we wish you all the best in your pursuit of fame and fortune. Please take a moment to ask yourself whether you just want to be the rave of the moment or you want to be eternal. For your information, in this industry, a phenomenon is usually over in 18 months or thereabout.<br><br>

<p><strong>Q: Ok. So what exactly will an A&R consultant do for me?</strong><br>
A: An A&R consultant will first and foremost help you find out if you indeed possess the talent and attitude required to successfully pursue a career in  music. Next, he’ll be listening up to ascertain the  “excellence  of execution” in your recordings. This means he will be paying close attention to your lyrics, clarity and uniqueness of your style of rapping/singing, songwriting, arrangement and also discovering what kind of emotions the songs are likely to evoke in your listeners. He’ll want to be sure your recordings are on the cutting edge of contemporary Hip Hop/R&B music. He will also be paying close attention to technical things like running time of individual tracks and the entire recording, mixing and mastering.  Your live performance is also under scrutiny. This is to help determine the general likeability of you and your work by the target demographic. All this is necessary if you do not have music enthusiasts in your circle of friends and associates.<br><br>

<p><strong>Q: So at what point in the creative process does the A&R guy come in? I’ve already recorded all the songs.</strong><br>
A: He typically comes in at this point, i.e. when you have already recorded all the songs you want, and have done the initial mixes. It will cost you more in terms of cost of production  for songs that he axes if he came in at a later stage. But even this is a token compared to what you lose when you  try to promote  an inferior recording.<br><br>

<p><strong>Q: All of these sound like what a producer can do. Why do I need an A&R guy when a producer can do all these?</strong><br>
A: Well, most.  But you have to understand something: save for the big name producers, most of your average Hip Hop/R&B producers are typically beatmakers i.e. they just craft backing tracks and hand them over to the artists who do pretty much what they like when they voice it – elsewhere. There are some who will guide your vocals though.  But truth is, if you’re new in the game and you don’t make a great first impression on a producer, big name or not, he is unlikely to give his best when working with you, especially when you’re not paying top dollar! That’s why the attitude bit of an A&R session is necessary.<br><br>

<p><strong>Q: This all sounds very subjective. The A&R guy can make wrong judgements, he is human after all, or isn’t he?</strong><br>
A: Yes he is human. And yes, he can make wrong judgements. That’s why a full A&R session is neither a one-man show nor a one-off event. It involves a team of experts - the consultant, a seasoned music critic, a producer and a radio personality – coming together to assess an act, live and recorded. You can liken their work to that of the F.A.’s  Appeals Committee which is made up of “football people” who go through the appeals of prospective EPL players who have been denied work permit on their initial application. As a collective they seldom make wrong judgements.<br><br>
<p><strong>Q: So how much does it cost to see an A&R consultant?</strong><br>
A: Initial meetings typically cost less than it does to book a full studio session. Clients are usually billed on an hourly basis.
 
    



	
</p>


							</div>

			
<div id="comments" class="comments-area">

	
</div>			</article>
				</div>
					</div>

	</div>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/srrp.html.erb
<div id="content" class="site-content">

      

<div class="header-title without-cap text-center" style="background: url(https://s3.amazonaws.com/sparta30/photo/danny-howe-365401.jpg); background-size: cover;">
  <div class="title-wrap">
    <div class="content">
    
      <div class="full-width-container">
        <h1 class="page-title">Sparta Inc.</h1>
                  <br>
          <p class="subtitle">Know your Music. Master your Craft.</p>
              </div>

    </div>
  </div>
</div> <!-- .header-title -->
<div class="container">
					<h1>SRRP Q & A</h1><span class="heading-b3" style="margin-top:px; margin-bottom:px; background-color:#000000"></span>				
			
			<div class="entry">



<p><strong>Q: 	What is a Synchronized Radio Release Party (SRRP)?</strong></p>
A:	A Synchronized Radio Release Party is a recreation of an album release party complete with eats and drinks in the studio of radio stations across the country at the same time. It could be done before, after or at the same time as the actual album launch.

<p><strong>Q:	Why do I need to have a SRRP?</strong></p>
A:	The same reason why you have an album launch: To generate buzz for new album/EP
 
<p><strong>Q:	Isn’t it enough that I am having an album launch and actively promoting it on social media?</strong></p>
A:	Yes and No. Yes if you are an A-list artist who is very much in the limelight. But if you are new, make niche music or are a comebacking former A-lister, then an SRRP is an ABSOLUTE necessity. Let me explain. Urban radio DJs and O-A-Ps still wield considerable power as music tastemakers and pop culture influencers. While it is possible to warm up to and indeed befriend – or purchase the loyalty of  - a majority of the Radio DJs and O-A-Ps in the Mecca of the Nigerian Music industry that is Lagos, it is a lot more difficult doing the same to a lot of the other urban radio stations scattered across the country. An SRRP is an effective way of  bridging this gap.

<p><strong>Q:	What are the real benefits of having an SRRP?</strong></p> 
 A(i):	Better aggregate mileage than you would get if you are a newbie hosting a release party with a less than stellar line up at a not-so-swank venue.
(ii):	More value for money. An SRRP costs less than the rent for the Expo Hall of Eko Hotel or any other prestigious venue.
(iii):	Hard data to analyse and exploit for sales and promotion as there are dedicated social media handles i.e on Twitter, Instagram, Facebook and Youtube for every SRRP, it is easy to collate data on the activation.
(iv):	A real relationship with the radio stations where an SRRP is activated. The goodwill received from the various radio stations upon activation of an SRRP can be easily transformed into a real relationship with the DJs and O-A-Ps by the artist and his management.
(v):	There is cost flexibility in having an SRRP as client can pick and choose the stations where they want activations done. However, we recommend that clients do activations in at least a dozen (12) stations spread across either the artist’s area of strength or cities that are key music markets.
(vi): Direct feedback from all the radio stations to the artist’s manager/label rep upon receipt of the SRRP promo pack.
vii): Many minutes of on air O-A-P hype on the day of release and many days/ weeks after.

<p><strong>Q:	Can you walk me through the process of having an SRRP?</strong></p>
A:	It start with picking a date for the activation. Then it moves on to making the promo materials i.e  complimentary copies of the album, copies of the CD sampler* and the album release posters. All of these materials must be made available to us at least a week before the activation date. We’ll take it from there.
* A CD sampler in this case is a specially recorded EP containing songs off the album being released. It typically contains the singles plus one or two focus tracks. Such samplers usually have these songs remixed, remade or retooled, and are made exclusively for the radio stations where activations will be done. They can also take the form of a concept album, a sonic recreation of a typical album launch where there are distinct segments like the red carpet, the show and the after party. This CD sampler and its exclusivity is key in “igniting” the released party in the studios of the radio stations slated for activation.

<p><strong>Q:	 Why should I “serve” food and drinks to the DJs and O-A-Ps at the various stations? Wouldn’t it be better if I just gave them money?</strong></p>
A:	Because you are hosting a party. Besides, what better way is there to “ sweet talk” the contemporary Nigerian into doing what you want other than giving them something wonderful to eat and something great to drink?

 	



<h4>RADIO STATIONS</h4>
 
1. Rave FM, Osogbo</br>
2. Gravity FM, Oyo</br>
3. Amana FM, Gombe</br>
4. Search FM, Minna</br>
5. Hot FM. Asaba</br>
6. Kiss FM, Abuja</br>
7. Rhythm FM, Abuja</br>
8. Urban FM,Enugu</br>
9. Inspiration FM, Ibadan</br>
10. Hit FM, Calabar</br>
11. Solid  FM, Enugu</br>
12. Dream FM, Enugu</br>
13. Love FM, PH</br>
14. Splash FM, Ibadan</br>
15. Canaan City FM, Calabar</br>
16. Creek FM, Yenagoa</br>
17. Radio Benue 2, Makurdi</br>
18. Atlantic FM, Uyo</br>
19. Heartland FM, Owerri</br>
20. Trend FM, Asaba</br>
21. Magic FM, Aba</br>
22. Bronze FM, Benin City</br>
23. Orange FM, Akure</br>
24. Vibes FM, Benin City</br>
25. Rock City FM, Abeokuta</br>
26. UniQ FM, Ilesha</br>
27. Breez FM, Akure</br>
28. Inspiration FM, Uyo</br>
29. Coal City FM, Enugu</br>
30. Unity FM, Abakaliki</br>
31. Freedom FM, Kaduna</br>
32. Vison Africa FM, Umuahia</br>
33. Independent Radio, Benin City</br>
34. Okin FM, Offa</br>
35. BRC FM, Bauchi</br>
36. Hot FM, Abuja</br>
37. Brila FM, Onitsha</br>
38. BSES FM, Ado-Ekiti</br>
39. Freedom FM, Kano</br>
40. Liberty Radio, Kaduna</br>
41. Progress FM, Ado-Ekiti</br>
42. Hot FM, Owerri</br>
43. Cool FM, PH</br>
44. Rhythm FM,PH</br>
45. Gold FM, Ilesha.</br>
46. Paradise FM, Calabar</br>
47. Brila FM, Kaduna</br> 
48. Brila FM, Abuja</br>
49. Beat FM, Ibadan</br>
50. Cool FM, Kano</br>
51. Positive FM, Akure</br>
52. Human Rights Radio, Abuja</br>
53. Radio Sapientia, Onitsha</br>
54. Wazobia FM, Abuja</br>
55. Adaba FM, Akure</br> 
56. Raypower FM, Abuja</br>
57. Zuma FM, Suleja</br>
58. Darling FM, Owerri</br>
59. Bridge FM, Asaba</br>
60. Companion FM, Katsina</br>






 










	
</p>


							</div>

			
<div id="comments" class="comments-area">

	
</div>			</article>
				</div>
					</div>

	</div>