config/routes.rb
Rails.application.routes.draw do

  resources :messengers
  devise_for :users
  resources :services
  root 'pages#landing'

  %q{get '/about' => 'pages#about'

  get '/contact' => 'pages#contact'

  get '/faqs' => 'pages#faqs'

  get '/qanda' => 'pages#srrp'}

end

app/models/messenger.rb
class Messenger < ApplicationRecord

	validates :name, presence: true
    validates :message, presence: true
    validates :subject, presence: true
    validates :email, presence: true



end

app/controllers/messengers_controller.rb
class MessengersController < ApplicationController
  before_action :set_messenger, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, only: [:index, :edit, :update, :destroy]
  # GET /messengers
  # GET /messengers.json
  

  # GET /messengers/new
  def new
    @messenger = Messenger.new
  end

 

  # POST /messengers
  # POST /messengers.json
  def create
    @messenger = Messenger.new(messenger_params)

    respond_to do |format|
      if @messenger.save
        MessengerMailer.contact_mail(@messenger).deliver_now
        format.html { redirect_to root_url, notice: 'Messsage was successfully sent.' }
        format.json { render :show, status: :created, location: root_url }
      else
        format.html { redirect_to root_url, notice: @messenger.errors}
        format.json { render json: @messenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messengers/1
  # PATCH/PUT /messengers/1.json
  
  # DELETE /messengers/1
  # DELETE /messengers/1.json
  def destroy
    @messenger.destroy
    respond_to do |format|
      format.html { redirect_to messengers_url, notice: 'Messenger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_messenger
      @messenger = Messenger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def messenger_params
      params.require(:messenger).permit(:name, :email, :subject, :message)
    end
end

app/helpers/messengers_helper.rb
module MessengersHelper
end

app/views/messengers/_form.html.erb
<%= form_for(@messenger) do |f| %>
  <% if @messenger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@messenger.errors.count, "error") %> prohibited this messenger from being saved:</h2>

      <ul>
      <% @messenger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'YOUR NAME', class: 'form-control', id: "exampleInputEmail1", aria_describedby: "emailHelp" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, placeholder: 'YOUR EMAIL', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject, placeholder: 'SUBJECT', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :message %>
    <%= f.text_area :message, placeholder: 'YOUR MESSAGE', class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'SUBMIT',class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/messengers/edit.html.erb
<h1>Editing Messenger</h1>

<%= render 'form', messenger: @messenger %>

<%= link_to 'Show', @messenger %> |
<%= link_to 'Back', messengers_path %>

app/views/messengers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messengers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Subject</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messengers.each do |messenger| %>
      <tr>
        <td><%= messenger.name %></td>
        <td><%= messenger.email %></td>
        <td><%= messenger.subject %></td>
        <td><%= messenger.message %></td>
        <td><%= link_to 'Show', messenger %></td>
        <td><%= link_to 'Edit', edit_messenger_path(messenger) %></td>
        <td><%= link_to 'Destroy', messenger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Messenger', new_messenger_path %>

app/views/messengers/new.html.erb
<h1>New Messenger</h1>

<%= render 'form', messenger: @messenger %>

<%= link_to 'Back', messengers_path %>

app/views/messengers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @messenger.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @messenger.email %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @messenger.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @messenger.message %>
</p>

<%= link_to 'Edit', edit_messenger_path(@messenger) %> |
<%= link_to 'Back', messengers_path %>